version: '3.8'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules  # Ensure fresh install inside container (prevents conflicts)
